sudo: false
dist: trusty
group: edge
language: php
php:
  - 5.6
  - 7.0
  - hhvm-3.3
  - hhvm-3.6
  - hhvm-3.9
  - hhvm-3.12
  - nightly

cache:
  directories:
    - ~/.composer/cache/files/

install:
  - composer install

before_script:
  # Ancient make binary at TravisCI doesn't support indentation with spaces
  - unexpand -t 4 Makefile > Makefile.tmp && mv Makefile.tmp Makefile

script:
  - make test

branches:
  only: [master, develop]
